---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-03 - 03:58:39 +0000
  labels:
    app.kubernetes.io/name: tp-rest
    app.kubernetes.io/version: "1.0"
  name: tp-config-map
  namespace: tp
data:
  app.file: |
    key=value
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-03 - 03:58:39 +0000
  labels:
    app.kubernetes.io/name: tp-rest
    app.kubernetes.io/version: "1.0"
  name: tp-rest
  namespace: tp
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: tp-rest
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-03 - 03:58:39 +0000
  labels:
    app.kubernetes.io/name: tp-rest
    app.kubernetes.io/version: "1.0"
  name: tp-rest
  namespace: tp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tp-rest
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-07-03 - 03:58:39 +0000
      labels:
        app.kubernetes.io/name: tp-rest
        app.kubernetes.io/version: "1.0"
      namespace: tp
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: tp-config-map
          image: quay.io/masood_faisal/demo-app:1.0
          imagePullPolicy: Always
          name: tp-rest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /tp/app
              name: my-volume
              readOnly: false
      volumes:
        - configMap:
            defaultMode: 384
            name: tp-config-map
            optional: false
          name: my-volume
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: tp-rest-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
#spec:
#  rules:
#    - host: hello-world.info
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: tp-rest
#                port:
#                  name: http
